# Generated by Django 5.0 on 2024-01-07 17:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, default='hi', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='images/projects/'),
            preserve_default=False,
        ),
    ]
